apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: {{ .Values.service.type }}
  selector:
    # Labels are used as selectors.
    project: roboshop
    purpose: helm-demo
  ports:
  - protocol: TCP
    port: 80          # Service Port
    targetPort: 80    # Container Port 